app:
  version: 1.0.0
logging:
  level:
    org.springframework.web: DEBUG

server.port: 8086

spring:

  #Kafka
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    consumer:
      group-id: halco
    listener:
      ack-mode: RECORD

  datasource:

    driver-class-name: org.postgresql.Driver
    platform: postgres

    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true

    #deployed postgres
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    locations: classpath:db/migration
    check-location: true
    baseline-on-migrate: true
    driverClassName: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  ### SMTP ###
  mail:
    host: smtp.office365.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

jwt-secret-key: ${JWT_SECRET_KEY}